### ISSUE TITLE
Where do you get Azure ClientID and TenantID?

### ISSUE THREAD

**Issue by IronSean** [feeloor/azure-static-website-deploy#2]
Could there be more documentation around setting up the Azure side of this? I'm not sure which services I need to enable to get client and tenant IDs

**Comment by benmccallum** [comment]
+1, I'm a bit lost on this too.

I've managed to find [this](https://docs.microsoft.com/en-us/azure/storage/common/authorize-data-operations-cli?toc=/azure/storage/blobs/toc.json) about AZ auth, and the env vars almost match, but not 100%. 

Just gonna use the cli direct via [Azure Login](https://github.com/marketplace/actions/azure-login) in the meantime.

**Comment by feeloor** [comment]
Hi @IronSean & @benmccallum!

1. Navigate to Azure Active Directory
2. Select App Registrations
3. Create a new application or use an existing
4. In overview of your application you'll be able to see your Client/Tenant ID.

Please let me know if you are having issues finding it.
