### ISSUE TITLE
Action is now broken

### ISSUE THREAD

**Issue by lgmorand** [feeloor/azure-static-website-deploy#4]
Hello @feeloor @vadim-kovalyov 

I'm using your action for months without any issue but it seems they changed something **on Github side**. All my pipelines using your task are now broken during setup (https://github.com/lgmorand/aks-checklist/runs/949950370)

They do not seem to like the fact so you specificy "outputs:" by being empty.

`##[error]feeloor/azure-static-website-deploy/v0.1.0/action.yml (Line: 32, Col: 9): Unexpected value ''
##[error]feeloor/azure-static-website-deploy/v0.1.0/action.yml (Line: 32, Col: 9): Unexpected value ''
##[error]System.ArgumentException: Unexpected type 'NullToken' encountered while reading 'outputs'. The type 'MappingToken' was expected.`

Could you publish a version 0.1.1 without this output parameter to see if that fixes it ?

for info, to test the fix, I created my v0.1.1, removed outputs and it works: https://github.com/lgmorand/aroworkshop/runs/949981314?check_suite_focus=true
But since you are the original authors, I prefer to continue to use yours <3 

Thanks

Note: microsoft CLI image has moved, you should point to the new repo: https://hub.docker.com/r/microsoft/azure-cli
and specify: mcr.microsoft.com/azure-cli

**Comment by nbarrasson** [comment]
Same issue there:
`feeloor/azure-static-website-deploy/v0.1.0/action.yml (Line: 32, Col: 9): Unexpected value ''`

**Comment by lgmorand** [comment]
Sadly, there is the bug in the YAML action file but besides, bad timing, an known issue with the CLI discovered yesterday: https://github.com/Azure/azure-cli/issues/14641

Fix for CLI will be deployed in 3 weeks... workaround is to specify the CLI version to 2.9.1 (https://github.com/Azure/azure-cli/issues/14641#issuecomment-669080810)

**Comment by vadim-kovalyov** [comment]
Thanks @lgmorand for reporting the issue. I'm not an active member of this repo. I would suggest to open a PR with the fix, if you can. That's what I did last time when I was playing with this action.

**Comment by lgmorand** [comment]
Done. #5 

One remark, my fix is working and clean (I tested it) but it will totally work once they fixed and update the mcr.microsoft.com/azure-cli docker image.

**Comment by feeloor** [comment]
Thanks for reporting this @lgmorand, I'll review the PR and publish it. 
Thanks for your contribution! 👍 💯

**Comment by feeloor** [comment]
I've now merged your changes @lgmorand, please feel free to reopen the issue if the problem persists. 
Thanks again!

**Comment by lgmorand** [comment]
They updated the docker image (https://hub.docker.com/r/microsoft/azure-cli/) and now the action is still fully fonctional

**Comment by feeloor** [comment]
@lgmorand That's great news, thanks for your contribution! 💯
